/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueAccrualRouteImport } from './routes/value-accrual'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValueAccrualIndexRouteImport } from './routes/value-accrual.index'
import { Route as ValueAccrualFlowchartRouteImport } from './routes/value-accrual.flowchart'
import { Route as ValueAccrualCompareRouteImport } from './routes/value-accrual.compare'
import { Route as ValueAccrualProtocolIdRouteImport } from './routes/value-accrual.$protocolId'
import { Route as TokensTokenIdRouteImport } from './routes/tokens/$tokenId'

const ValueAccrualRoute = ValueAccrualRouteImport.update({
  id: '/value-accrual',
  path: '/value-accrual',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueAccrualIndexRoute = ValueAccrualIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ValueAccrualRoute,
} as any)
const ValueAccrualFlowchartRoute = ValueAccrualFlowchartRouteImport.update({
  id: '/flowchart',
  path: '/flowchart',
  getParentRoute: () => ValueAccrualRoute,
} as any)
const ValueAccrualCompareRoute = ValueAccrualCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => ValueAccrualRoute,
} as any)
const ValueAccrualProtocolIdRoute = ValueAccrualProtocolIdRouteImport.update({
  id: '/$protocolId',
  path: '/$protocolId',
  getParentRoute: () => ValueAccrualRoute,
} as any)
const TokensTokenIdRoute = TokensTokenIdRouteImport.update({
  id: '/tokens/$tokenId',
  path: '/tokens/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/value-accrual': typeof ValueAccrualRouteWithChildren
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/value-accrual/$protocolId': typeof ValueAccrualProtocolIdRoute
  '/value-accrual/compare': typeof ValueAccrualCompareRoute
  '/value-accrual/flowchart': typeof ValueAccrualFlowchartRoute
  '/value-accrual/': typeof ValueAccrualIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/value-accrual/$protocolId': typeof ValueAccrualProtocolIdRoute
  '/value-accrual/compare': typeof ValueAccrualCompareRoute
  '/value-accrual/flowchart': typeof ValueAccrualFlowchartRoute
  '/value-accrual': typeof ValueAccrualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/value-accrual': typeof ValueAccrualRouteWithChildren
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/value-accrual/$protocolId': typeof ValueAccrualProtocolIdRoute
  '/value-accrual/compare': typeof ValueAccrualCompareRoute
  '/value-accrual/flowchart': typeof ValueAccrualFlowchartRoute
  '/value-accrual/': typeof ValueAccrualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/value-accrual'
    | '/tokens/$tokenId'
    | '/value-accrual/$protocolId'
    | '/value-accrual/compare'
    | '/value-accrual/flowchart'
    | '/value-accrual/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/tokens/$tokenId'
    | '/value-accrual/$protocolId'
    | '/value-accrual/compare'
    | '/value-accrual/flowchart'
    | '/value-accrual'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/value-accrual'
    | '/tokens/$tokenId'
    | '/value-accrual/$protocolId'
    | '/value-accrual/compare'
    | '/value-accrual/flowchart'
    | '/value-accrual/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  ValueAccrualRoute: typeof ValueAccrualRouteWithChildren
  TokensTokenIdRoute: typeof TokensTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value-accrual': {
      id: '/value-accrual'
      path: '/value-accrual'
      fullPath: '/value-accrual'
      preLoaderRoute: typeof ValueAccrualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value-accrual/': {
      id: '/value-accrual/'
      path: '/'
      fullPath: '/value-accrual/'
      preLoaderRoute: typeof ValueAccrualIndexRouteImport
      parentRoute: typeof ValueAccrualRoute
    }
    '/value-accrual/flowchart': {
      id: '/value-accrual/flowchart'
      path: '/flowchart'
      fullPath: '/value-accrual/flowchart'
      preLoaderRoute: typeof ValueAccrualFlowchartRouteImport
      parentRoute: typeof ValueAccrualRoute
    }
    '/value-accrual/compare': {
      id: '/value-accrual/compare'
      path: '/compare'
      fullPath: '/value-accrual/compare'
      preLoaderRoute: typeof ValueAccrualCompareRouteImport
      parentRoute: typeof ValueAccrualRoute
    }
    '/value-accrual/$protocolId': {
      id: '/value-accrual/$protocolId'
      path: '/$protocolId'
      fullPath: '/value-accrual/$protocolId'
      preLoaderRoute: typeof ValueAccrualProtocolIdRouteImport
      parentRoute: typeof ValueAccrualRoute
    }
    '/tokens/$tokenId': {
      id: '/tokens/$tokenId'
      path: '/tokens/$tokenId'
      fullPath: '/tokens/$tokenId'
      preLoaderRoute: typeof TokensTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ValueAccrualRouteChildren {
  ValueAccrualProtocolIdRoute: typeof ValueAccrualProtocolIdRoute
  ValueAccrualCompareRoute: typeof ValueAccrualCompareRoute
  ValueAccrualFlowchartRoute: typeof ValueAccrualFlowchartRoute
  ValueAccrualIndexRoute: typeof ValueAccrualIndexRoute
}

const ValueAccrualRouteChildren: ValueAccrualRouteChildren = {
  ValueAccrualProtocolIdRoute: ValueAccrualProtocolIdRoute,
  ValueAccrualCompareRoute: ValueAccrualCompareRoute,
  ValueAccrualFlowchartRoute: ValueAccrualFlowchartRoute,
  ValueAccrualIndexRoute: ValueAccrualIndexRoute,
}

const ValueAccrualRouteWithChildren = ValueAccrualRoute._addFileChildren(
  ValueAccrualRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  ValueAccrualRoute: ValueAccrualRouteWithChildren,
  TokensTokenIdRoute: TokensTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
